<a href="https://colab.research.google.com/github/manikur/R-programming/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt

In [4]:
a = 2
b = 3
c = tf.add(a, b, name='Add')
print(c)

tf.Tensor(5, shape=(), dtype=int32)


In [6]:
c = tf.constant([[2.0, 3.0], [1.0, 4.0]])
d = tf.constant([[1.0, 2.0], [0.0, 1.0]])
e = tf.matmul(c, d)
print (e)

tf.Tensor(
[[2. 7.]
 [1. 6.]], shape=(2, 2), dtype=float32)


In [11]:
number_of_datapoints = 100
# generate random x values in the range -6 to +6
x = np.random.uniform(low = -6 , high = 6 ,
size = (number_of_datapoints, 1))
x[:6,:].round(2)

array([[-1.33],
       [-1.17],
       [-5.23],
       [-0.91],
       [-4.69],
       [-0.25]])

In [12]:
# Define the data as constants.
X = tf.constant([[1, 0], [1, 2]], tf.float32)
Y = tf.constant([[2], [4]], tf.float32)
# Initialize beta.
beta = tf.Variable([[0.01],[0.01]], tf.float32)
# Compute the residual.
residuals = Y - tf.matmul(X, beta)

In [14]:
# Define two scalars as constants.
s1 = tf.constant(5, tf.float32)
s2 = tf.constant(15, tf.float32)
# Add and multiply using tf.add() and tf.multiply().
s1s2_sum = tf.add(s1, s2)
s1s2_product = tf.multiply(s1, s2)
print(s1s2_sum,s1s2_product)


tf.Tensor(20.0, shape=(), dtype=float32) tf.Tensor(75.0, shape=(), dtype=float32)


In [18]:
# Generate 6-tensors from normal distribution draws.
A = tf.random.normal([5, 10, 7, 3, 2, 15])
B = tf.random.normal([5, 10, 7, 3, 2, 15])
# Perform elementwise multiplication.
C = tf.multiply(A, B)
C = A*B
print(C)

tf.Tensor(
[[[[[[-7.26869941e-01  1.34521484e-01  1.38233685e+00 ...
       8.56840312e-01 -5.90250015e-01  6.91034198e-02]
     [-1.71140468e+00 -2.96989501e-01 -7.33425003e-03 ...
       2.72645772e-01  2.08129659e-02  6.83991551e-01]]

    [[ 1.84216835e-02  9.90760252e-02  1.83770377e-02 ...
      -3.97335052e-01  1.87284756e+00  6.95851564e-01]
     [-1.06824212e-01 -7.80103147e-01  5.64316325e-02 ...
       4.90703583e-01 -6.35050118e-01  1.72651798e-01]]

    [[ 1.26062199e-01 -3.00693866e-02  1.24076319e+00 ...
      -3.08637500e-01  1.01009381e+00  3.62085909e-01]
     [ 4.31330241e-02  2.60112733e-01 -1.77425385e-01 ...
      -1.49860114e-01  1.64687604e-01 -3.36756706e-01]]]


   [[[-1.86945312e-02 -1.54840663e-01 -1.20071888e+00 ...
      -2.11898685e-01  1.05865228e+00  4.77686584e-01]
     [-3.13692205e-02 -1.90967786e+00  3.23742890e+00 ...
       8.36264640e-02 -1.34762719e-01  1.06032777e+00]]

    [[ 2.42469534e-01  2.89223373e-01  3.68978083e-01 ...
      -2.34861791

In [19]:
# Set random seed to generate reproducible results.
tf.random.set_seed(1)
# Use normal distribution draws to generate tensors.
A = tf.random.normal([200])
B = tf.random.normal([200])
# Perform dot product.
c = tf.tensordot(A, B, axes = 1)
# Print numpy argument of c.
print(c.numpy())

-15.284362


In [20]:
# Use normal distribution draws to generate tensors.
A = tf.random.normal([200, 50])
B = tf.random.normal([50, 10])
# Perform matrix multiplication.
C = tf.matmul(A, B)
# Print shape of C.
print(C.shape)

(200, 10)


In [28]:
noise = np.random.uniform(low =-1 , high =1,
size = (number_of_datapoints, 1))

In [29]:
z = 7 * x + 6 * y + 5 + noise

In [33]:
input = np.column_stack((x,y))
print(input)

[[2. 8.]]


In [38]:
# Checking from equation
# z = 7*x + 6*y + 5
print("Expected output: ", 7*2 + 6*3 + 5)

Expected output:  37


In [40]:
# Set up data
number_of_datapoints = 1000
# generate random x values in the range -5 to +5
x = np.random.uniform(low = -5 , high = 5 , size = (number_of_datapoints, 1))

In [43]:
# generate random y values in the range -5 to +5
y = np.random.uniform(-5 , 5 , size = (number_of_datapoints , 1))
# generate some random error in the range -1 to +1
noise = np.random.uniform(low =-1 , high =1, size = (number_of_datapoints, 1))
z = 7 * x + 6 * y + 5 + noise

In [45]:
# Print x, y and z sample values for manual verification
x[:5,:].round(2)
y[:2,:].round(2)
z[:2,:].round(2)

array([[-3.2],
       [42.2]])

In [47]:
# Stack x and y arrays for inputting to neural network
input = np.column_stack((x,y))
# Print few values of input array for demonstration purpose.
input[:2,:].round(2)

array([[-2.88,  1.97],
       [ 2.93,  2.91]])